version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always

  rebase-labs:
    image: ruby
    container_name: rebase-labs
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    ports:
      - "3000:3000"
    command: bash -c "bundle install && ruby server.rb"
    restart: always

volumes:
  labs-gems: