#!/bin/bash

docker run \
  --rm \
  --name postgres \
  --network rebase-lab \
  -e POSTGRES_PASSWORD=password \
  -p 5432:5432 \
  -v $(pwd)/postgresdata:/var/lib/postgresql/data \
  -d \
  postgres

docker run \
  --rm \
  --name rebase-labs \
  --network rebase-lab \
  -w /app \
  -v $(pwd):/app \
  -v labs-gems:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && ruby server.rb"
